# Generated by Django 5.0.1 on 2024-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=20)),
                ('decr', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
                ('link', models.CharField(max_length=30)),
            ],
        ),
    ]
