# Generated by Django 5.0.1 on 2024-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
