# Generated by Django 5.0.1 on 2024-02-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0002_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coord',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=60),
        ),
    ]
