# Generated by Django 5.0.1 on 2024-02-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0003_event_coord_alter_event_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='coord',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='event',
            name='decr',
        ),
        migrations.AddField(
            model_name='event',
            name='decription',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tiny_decription',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
