# Generated by Django 5.0.1 on 2024-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0004_rename_coord_event_coordinates_remove_event_decr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tiny_decription',
            new_name='tiny_description',
        ),
        migrations.AlterField(
            model_name='event',
            name='coordinates',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
