# Generated by Django 5.0.1 on 2024-02-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0005_rename_decription_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
