# Generated by Django 5.0.1 on 2024-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0006_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
