# Generated by Django 5.0.1 on 2024-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0009_alter_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(default='Отсутствует', max_length=30),
        ),
    ]
