# Generated by Django 5.0.1 on 2024-03-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0010_event_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
