# Generated by Django 5.0.1 on 2024-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0012_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
    ]
