# Generated by Django 5.0.1 on 2024-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0014_alter_event_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
