# Generated by Django 4.2.6 on 2024-03-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0015_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
