# Generated by Django 4.2.6 on 2024-03-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0016_event_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('date_range_from', models.DateTimeField(blank=True, null=True)),
                ('date_range_to', models.DateTimeField(blank=True, null=True)),
                ('datetime_from_date', models.DateField(blank=True, null=True)),
                ('datetime_to_date', models.DateField(blank=True, null=True)),
                ('datetime_from_time', models.TimeField(blank=True, null=True)),
                ('datetime_to_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
    ]
