# Generated by Django 4.2.6 on 2024-03-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0017_datetimedata_remove_event_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimedata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
