# Generated by Django 4.2.6 on 2024-03-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0018_alter_datetimedata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
