# Generated by Django 4.2.6 on 2024-03-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0019_alter_datetimedata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimedata',
            name='date_range_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datetimedata',
            name='date_range_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
