# Generated by Django 4.2.6 on 2024-03-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0020_alter_datetimedata_date_range_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimedata',
            name='every_day',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
