# Generated by Django 4.2.6 on 2024-03-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0021_datetimedata_every_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
