# Generated by Django 4.2.6 on 2024-04-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0026_statsdate_statsdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsdays',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
