# Generated by Django 4.2.6 on 2024-04-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0027_event_likes_statsdays_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='bookmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsdays',
            name='bookmark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statsdays',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
