# Generated by Django 4.2.6 on 2024-04-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosug', '0028_bookmarks_event_bookmarks_statsdays_bookmark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statsdays',
            old_name='bookmark',
            new_name='bookmarks',
        ),
    ]
